---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stratus-v1
  namespace: stratus-dev
  labels:
    app: stratus
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stratus
      version: v1
  template:
    metadata:
      labels:
        app: stratus
        version: v1
    spec:
      serviceAccountName: stratus
      containers:
      - name: stratus
        image: registry.lestak.sh/stratus:v0.0.1
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - secretRef:
            name: stratus-v1
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
      imagePullSecrets:
      - name: regcred
