---
apiVersion: v1
kind: Service
metadata:
  name: stratus
  namespace: stratus-dev
  labels:
    app: stratus
spec:
  type: ClusterIP
  selector:
    app: stratus
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 80
